export { useAccessibilityPrefs } from './lib/useAccessibilityPrefs';
export {
  readAccessibilityPrefs,
  applyAccessibilityPrefsToRoot,
  persistAccessibilityPrefs,
  setAccessibilityPref,
  resetAccessibilityPrefs,
  EVENT_A11Y_PREFS_CHANGED,
  applyAccessibilityPreferences,
  getSystemTheme,
  getStoredTheme,
  setTheme,
  getSystemContrast,
  getStoredContrast,
  setContrast,
  getStoredDensity,
  setDensity,
  getStoredEvaluator,
  setEvaluator,
  getStoredMotion,
  setMotion,
  getStoredTextSize,
  setTextSize,
  getStoredLineHeight,
  setLineHeight,
  getStoredLetterSpacing,
  setLetterSpacing,
  getStoredDyslexiaFont,
  setDyslexiaFont,
  getStoredUnderlineLinks,
  setUnderlineLinks,
  computeEffectivePrefs,
  applyDocumentAttrs,
} from './lib/behavior-runtime';
export type {
  AccessibilityPrefs,
  AccessibilityPreferences,
  Theme,
  ResolvedTheme,
  ContrastMode,
  MotionPreference,
  TextSizePreference,
  LineHeightPreference,
  LetterSpacingPreference,
  EvaluatorMode,
  EffectivePrefs,
} from './lib/behavior-runtime';
