export {
  getSystemTheme,
  getStoredTheme,
  setTheme,
  getSystemContrast,
  getStoredContrast,
  setContrast,
  getStoredDensity,
  setDensity,
  getStoredEvaluator,
  setEvaluator,
  getStoredMotion,
  setMotion,
  getStoredTextSize,
  setTextSize,
  getStoredUnderlineLinks,
  setUnderlineLinks,
  computeEffectivePrefs,
  applyDocumentAttrs,
} from './lib/behavior-runtime';
export type {
  Theme,
  ResolvedTheme,
  ContrastMode,
  MotionPreference,
  TextSizePreference,
  EvaluatorMode,
  EffectivePrefs,
} from './lib/behavior-runtime';
